function [X,FVAL,EXITFLAG,OUTPUT,LAMBDA,GRAD,HESSIAN] = calibrationMertonbd(calltable,puttable)
    %
    %
   %
    Rate = 0.02;
    NumFFT = 2^12;
    DividendYield = 0;
    [m,~] = size(calltable);
    [n,~] = size(puttable);
    step = 1000;
    miter = floor(m/step);
    niter = floor(n/step);
    call = zeros(m,1);
    put = zeros(n,1);
    %
    %
    function ff = objfunc(x)
        %
        SigmaV = x(1);
        MeanJ = x(2);
        JumpVol = x(3);
        JumpFreq = x(4);
        %
        for i=1:miter
            linf = (i-1)*step + 1;
            lsup = i*step;
            callt = optByMertonFFT(Rate,calltable.stockprice(linf:lsup), ...
                        calltable.settle(linf:lsup), ...
                         calltable.maturity(linf:lsup),'call', ...
                         calltable.strike(linf:lsup),SigmaV,MeanJ, ...
                         JumpVol,JumpFreq,'DividendYield',DividendYield, ...
                         'NumFFT',NumFFT,'CharacteristicFcnStep',0.065, ...
                          'LogStrikeStep',0.001,'Basis',1);
            call(linf:lsup) = callt;
        end
        %
        for j=1:niter
            linf = (j-1)*step + 1;
            lsup = j*step;
            putt = optByMertonFFT(Rate,puttable.stockprice(linf:lsup), ...
                    puttable.settle(linf:lsup), ...
                         puttable.maturity(linf:lsup),'put', ...
                         puttable.strike(linf:lsup),SigmaV,MeanJ, ...
                         JumpVol,JumpFreq,'DividendYield',DividendYield, ...
                         'NumFFT',NumFFT,'CharacteristicFcnStep',0.065, ...
                          'LogStrikeStep',0.001,'Basis',1);
            put(linf:lsup) = putt;
        end
        %
        linf = miter*step + 1;
        lsup = m;
        callt = optByMertonFFT(Rate,calltable.stockprice(linf:lsup), ...
                        calltable.settle(linf:lsup), ...
                         calltable.maturity(linf:lsup),'call', ...
                         calltable.strike(linf:lsup),SigmaV,MeanJ, ...
                         JumpVol,JumpFreq,'DividendYield',DividendYield, ...
                         'NumFFT',NumFFT,'CharacteristicFcnStep',0.065, ...
                          'LogStrikeStep',0.001,'Basis',1);
        call(linf:lsup) = callt;
        %              
        %
        linf = niter*step + 1;
        lsup = n;
        putt = optByMertonFFT(Rate,puttable.stockprice(linf:lsup), ...
                    puttable.settle(linf:lsup), ...
                         puttable.maturity(linf:lsup),'put', ...
                         puttable.strike(linf:lsup),SigmaV,MeanJ, ...
                         JumpVol,JumpFreq,'DividendYield',DividendYield, ...
                         'NumFFT',NumFFT,'CharacteristicFcnStep',0.065, ...
                          'LogStrikeStep',0.001,'Basis',1);
        put(linf:lsup) = putt;
        %                          
       ff = sum(abs((call - calltable.price)./calltable.price)) + ...
            sum(abs((put - puttable.price)./puttable.price));
    end
    %
    lb = [0.01  -1  0.01   0.1];
    ub = [2.0    1  2.0   50.0];
    %
    %
    options = optimoptions('fmincon','Display','iter', ...
                            'MaxFunctionEvaluations',10000, ...
                            'Algorithm','interior-point');
    %
    x0 = [0.2 -0.1 0.05 1.7];
    [X,FVAL,EXITFLAG,OUTPUT,LAMBDA,GRAD,HESSIAN] = fmincon(@objfunc,x0, ...
                                    [],[],[],[],lb,ub,[],options);
    %
end